### ISSUE TITLE
Eliminate contention on thread semaphors

### ISSUE THREAD

**Issue by dgtony** [anytypeio/go-threads#2]
Continuation of https://github.com/anytypeio/go-anytype-library/issues/231

Currently go-threads have a simplistic implementation of synchronized processes working on each thread with mutual exclusion. It results in a huge semaphor acquiring times, stacked delays and finally leads to request failures.

- [x] Analyze semaphor statistics, collected on a cafe node
- [x] Recognize internal processes affected by semaphors
- [x] Propose new design, eliminating synchronization problems in Slack in Textile
- [x] Make implementation
- [x] Make PR back to textile repository including motivation and analysis
- [x] Test this version with `staging` / `python test`
- [x] Launch fixed version in the cafe to test with PR with stat in threads
- [x] `Get log` 
- [x] Close PR in https://github.com/textileio/go-threads/pull/435 and update our library

**Comment by d1eselboy** [comment]
`2 days for research and then estimate`

**Comment by d1eselboy** [comment]
We need to change library architecture
