### ISSUE TITLE
Hybrid model of storage. Logstore optimisation 

### ISSUE THREAD

**Issue by d1eselboy** [anytypeio/go-threads#4]
`Updated`
`till 14.10 and test`
`rollout 15.10 and test`
`if not ok will be in-memory`

Profiling our cafe service under the load reveals that go-threads currently spend a lot of time in its logstore component.
Logstore in itself is an aggregating service around the group of datastores containing keys, addresses, log heads etc. Each datastore is implemented with its own set of internal locks, implicit transactions and so on, and, taking into account complex trees of subrequests originating from the logstore' methods, currently we have a performance bottleneck here.
At the same time it's pretty clear that logstore requests are highly skewed towards the reading, while writes are relatively rare, and it holds out hope that we can improve performance introducing additional caching layer(s).
In this research we're trying to move in two directions: narrowing down frequency and amount of information requested from the logstore, and finding out optimal caching scheme for reducing logstore' read latency.

**Comment by dgtony** [comment]
Profiling our cafe service under the load reveals that `go-threads` currently spend a lot of time in its `logstore` component.
Logstore in itself is an aggregating service around the group of datastores containing keys, addresses, log heads etc. Each datastore is implemented with its own set of internal locks, implicit transactions and so on, and, taking into account complex trees of subrequests originating from the logstore' methods, currently we have a performance bottleneck here.
At the same time it's pretty clear that logstore requests are highly skewed towards the reading, while writes are relatively rare, and it holds out hope that we can improve performance introducing additional caching layer(s).
In this research we're trying to move in two directions: narrowing down frequency and amount of information requested from the logstore, and finding out optimal caching scheme for reducing logstore' read latency.

**Comment by dgtony** [comment]
Upstream PR: https://github.com/textileio/go-threads/pull/463
