### ISSUE TITLE
GetRecords handler. Heads state API

### ISSUE THREAD

**Issue by d1eselboy** [anytypeio/go-threads#6]
`till 16.12`
`till 17.12`

**Problem**
Node, polling other nodes for a new thread, can get the whole GetRecords answer even if synchronized.

**Idea**
We can set up the API that will have reduced message size and other logic, so traffic and computational complexity will reduce. 

**Solution**
We need to add a new request/response pair to the protocol: each peer will get a request with some hash reflecting the current state of the heads of the requesting node. If the sender will have the same coincidental state as the recipient, the node will consider itself synchronized. Otherwise, a full GetRecords request will follow, pulling updates.

UPD
We won't update protocol → just handler

**Comment by dgtony** [comment]
Related PR: https://github.com/textileio/go-threads/pull/471

**Comment by dgtony** [comment]
MW PR: https://github.com/anytypeio/go-anytype-middleware/pull/847
